name: CI (Release)
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish -p:PublishSingleFile=true -p:CommitHash=${{ github.sha }} -p:CommitRef=${{ github.ref_type }}/${{ github.ref_name }} -r win-x64 -c Release --self-contained false .\Bloxstrap\Bloxstrap.csproj

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Fishstrap (Release) (${{ github.sha }})
        path: .\Bloxstrap\bin\Release\net6.0-windows\win-x64\publish\*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Fishstrap (Release) (${{ github.sha }})
          path: release

      - name: Rename binaries
        run: mv release/Bloxstrap.exe Fishstrap-${{ github.ref_name }}.exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: Fishstrap-${{ github.ref_name }}.exe
          name: Fishstrap ${{ github.ref_name }}

  release-test:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/release-test')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Fishstrap (Release) (${{ github.sha }})
          path: release

      - name: Rename binaries
        run: mv release/Bloxstrap.exe Fishstrap-${{ github.ref_name }}.exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: Fishstrap-${{ github.ref_name }}.exe
          name: Fishstrap ${{ github.ref_name }}
